### ISSUE TITLE
Eclipse JPA - Generate Entity from Table No Schema

### ISSUE THREAD

**Issue by JohneDoe** [mrotteveel/fbdtp#1]
Database Development WORKS! (after rederencing new
 driver)

BUT!

JPA-Folder-> New File -> JPA Entity From Table. Combox Schems is not Filled. 

I have no knoledge in EclipeRCP dev.
but..
org.eclipse.jpt.jpa.db.internal.driver.DTPDriverAdapterManager

```
private void addAdapterFactoriesTo(HashMap<String, DTPDriverAdapterFactory> factories)
  {
    addAdapterFactoryTo(new DB2.Factory(), factories);
    addAdapterFactoryTo(new Derby.Factory(), factories);
    addAdapterFactoryTo(new HSQLDB.Factory(), factories);
    addAdapterFactoryTo(new Informix.Factory(), factories);
    addAdapterFactoryTo(new MaxDB.Factory(), factories);
    addAdapterFactoryTo(new MySQL.Factory(), factories);
    addAdapterFactoryTo(new Oracle.Factory(), factories);
    addAdapterFactoryTo(new PostgreSQL.Factory(), factories);
    addAdapterFactoryTo(new SQLServer.Factory(), factories);
    addAdapterFactoryTo(new Sybase.Factory(), factories);
  }
```

**Comment by mrotteveel** [comment]
Interesting that they 'abandon' the plugin model there and hard code the dependencies.

I will need to investigate this further, but it looks like this can't be fixed without getting this plugin into Eclipse itself.

**Comment by JohneDoe** [comment]
Today in tested it again.
Eclipse NEON->JPA-Folder-> New File -> JPA Entity From Table.
WORKS!!
